
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-20T11:59:35-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c806cba2d876746cecb48a21a68e7298875308d8",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
