
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-08T15:36:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c7574fbe80d8f0906f485072d50f4ea3f1fd8f6",
 "version": "1.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
