
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-02-22T17:47:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "396f9a4e4ab7ca368bac4d7b785e90a53d4d5fd5",
 "version": "1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
