
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-28T23:13:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "26d9567f56998ff7dbeac54d7a30a474a8ac3d8a",
 "version": "1.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
