
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-06-12T20:41:15+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c10df980f7049e01d3a8febcd2f347eb42a3c85",
 "version": "2.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
